; config file for various script constants
[general]
; frequency for serial emulator and serial reader (Hz)
write_freq = 2
read_freq = 1
; how many records need to be cached before sending to server
cache_size = 5

[calibration]
; a little too empirical for my liking but i dont know enough EE to understand why the board reports incorrect values
busv_fac = 1.
current_fac = 0.25
power_fac = 0.25
hall_speed_fac = 1.75

[limits]
; limits for sanity checks
; note: 12V battery maximum charge voltage 14.7V (6x 2.45V/cell)
; volts (voltage for 12v; 24v cancelled :sob:)
busv_min = 0
busv_max = 16
; amps
current_min = 0
current_max = 75
; km/h
hall_speed_min = 0
hall_speed_max = 50
